---
apiVersion: v1
kind: Namespace
metadata:
  name: catpump-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: layer2
      addresses:
      - 192.168.1.46/32
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catpump-api
  namespace: catpump-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catpump-api
  template:
    metadata:
      labels:
        app: catpump-api
    spec:
      containers:
      - name: catpump-api
        image: pgoode41/catpump-api
        ports:
        - name: http
          containerPort: 8085
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["SYS_ADMIN"]
          privileged: true
          allowPrivilegeEscalation: true
        #resources:
        #  limits:
        #    nvidia.com/gpu: 1 # requesting 1 GPU
---
apiVersion: v1
kind: Service
metadata:
  name: catpump-api-lb-service
  namespace: catpump-api
spec:
  ports:
  - name: http
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: catpump-api
  type: LoadBalancer











#sudo docker run -ti --rm -p 80:80 pgoode41/catpump-api-basic bash

