---
apiVersion: v1
kind: Namespace
metadata:
  name: catpump-update-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: layer2
      addresses:
      - 192.168.1.46/32
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catpump-update-service
  namespace: catpump-update-service
spec:
  selector:
    matchLabels:
      app: catpump-update-service
  template:
    metadata:
      labels:
        app: catpump-update-service
    spec:
      containers:
      - name: catpump-update-service
        image: pgoode41/catpump-update-service
        ports:
        - name: http
          containerPort: 8075

---
apiVersion: v1
kind: Service
metadata:
  name: catpump-update-service
  namespace: catpump-update-service
spec:
  ports:
  - name: http
    port: 8075
    protocol: TCP
    targetPort: 8075
  selector:
    app: catpump-update-service
  type: LoadBalancer






#sudo docker build Update_Service/ -t pgoode41/catpump-update-service && sudo docker push pgoode41/catpump-update-service && sudo docker pull pgoode41/catpump-update-service 




#sudo docker run -ti --rm -p 80:80 pgoode41/catpump-update-service-basic bash
